
class Error(Exception):
    pass

class UndoServiceException(Error):
    pass